//! Behaviour-clone a policy from the corpus of clearing trajectories.
//!
//! ```text
//! read the per-faction corpus
//!   -> replay a batch of trajectories, forcing their recorded decisions
//!   -> collect (features, demonstrated action) at every non-forced decision
//!   -> one gradient step on  -(1/N) sum log pi(a|s)
//!   -> measure greedy clearance on the Validation pool
//! ```
//!
//! # Why it streams
//!
//! The corpus stores specifications, not features, so features are regenerated by replay. Holding
//! them all would be the feature dump the corpus exists to avoid — 103,665 trajectories at ~50
//! decisions and ~10 options each is hundreds of millions of numbers. So a batch of trajectories is
//! replayed, turned into demonstrations, stepped on, and discarded.
//!
//! Replay is the cost: about 128 games a second, so an epoch is bounded by how many trajectories it
//! draws rather than by the optimiser. `--per-epoch` sets that, sampled **balanced across
//! factions**, because the corpus yield is uneven — Sol and L1Z1X contribute ~24k each and Letnev
//! and Jol-Nar ~10k — and pooling it raw would train twice as hard on two factions for no reason
//! other than filter rate.
//!
//! Drawing equal numbers of trajectories is **not** the same as balancing the gradient, and an
//! earlier version of this confused the two. The loss is over decisions, and Hacan runs 79.5 of them
//! a trajectory against L1Z1X's 43.8 — nearly all free transactions — so equal trajectory counts
//! still delivered 1.8x the gradient to Hacan. Each demonstration now carries `1 / decisions` for
//! its trajectory times `1 / trajectories` for its faction, so a trajectory counts once and a
//! faction counts once, whatever their lengths.
//!
//! # How a demonstration is extracted
//!
//! The seat is an `MlpBot` recording PPO steps, wrapped in a decider that **overrides its answer**
//! with the trajectory's recorded id. The bot still computes and records the position's features, so
//! the options are exactly what the current model would see; the game still follows the recorded
//! line, so the states are exactly the ones the demonstration visited. The bot's own choice is
//! discarded — the target is the recorded action's index, found by id and refused if absent.
//!
//! Forced decisions are skipped on both sides, matching the corpus.
//!
//! # Replay uses the frozen generating policy, never the one being trained
//!
//! A trajectory is a line played against five particular opponents. Replaying with the *live* actor
//! makes those opponents drift as training moves the weights, the game diverges, and the recorded
//! ids stop being on offer — replay failures climbed 176 to 876 out of 1,200 over twelve epochs and
//! the usable dataset collapsed from 54k demonstrations to 16k, silently and in the direction that
//! flatters the result, since the surviving lines are the ones least sensitive to the change.
//!
//! So every seat replays under the frozen bundle the corpus was generated from. This costs nothing:
//! the features come from `mlp_choice_features` and the vocabulary projection, neither of which
//! reads a weight, so the options recorded under the frozen actor are exactly the options the
//! trained model sees. Only the target — the recorded action — comes from the corpus, and only the
//! live actor is stepped.
//!
//! # Usage
//!
//! ```text
//! cargo run --release -p ti4-mlp --example corpus_train -- \
//!   --bundle out/checkpoints/sweep-A-250/checkpoint-14476 \
//!   --corpus out/corpus/positive --epochs 20 --out out/checkpoints/cloned
//! ```

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::rc::Rc;
use std::sync::Arc;

use rayon::prelude::*;
use ti4_content::ContentStore;
use ti4_engine::Choice;
use ti4_engine::choice::{ChoiceOption, Decider, IllegalChoice, SeatObservation};
use ti4_mlp::positive_corpus::{Demo, Trajectory, read_all};
use ti4_model::content_types::DEFAULT;
use ti4_model::id::{FactionId, PlayerId};

const FACTIONS: [&str; 6] = ["sol", "letnev", "xxcha", "hacan", "jolnar", "l1z1x"];
const TILE_SEED_OFFSET: u64 = 0;

fn argument(name: &str) -> Option<String> {
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        if arg == name {
            return args.next();
        }
    }
    None
}

fn refuse(reason: &str) -> ! {
    eprintln!("\nREFUSED: {reason}");
    std::process::exit(2);
}

fn number<T: std::str::FromStr>(flag: &str, fallback: T) -> T {
    argument(flag).map_or(fallback, |value| {
        value
            .parse()
            .unwrap_or_else(|_| refuse(&format!("{flag} expects a number")))
    })
}

/// Plays a recorded line, and records the index it forced at each decision.
struct Replaying {
    inner: Box<dyn Decider>,
    script: Vec<String>,
    at: usize,
    /// The option index taken at each non-forced decision, in order.
    forced: Rc<RefCell<Vec<usize>>>,
    /// Set when the script ran out or named an option that was not on offer.
    broken: Rc<RefCell<Option<String>>>,
}

impl Replaying {
    fn answer(
        &mut self,
        choice: &Choice,
        delegate: impl FnOnce(&mut Box<dyn Decider>) -> Result<ChoiceOption, IllegalChoice>,
    ) -> Result<ChoiceOption, IllegalChoice> {
        // Forced decisions carry no preference and are absent from the corpus, so they are answered
        // normally and do not advance the script. Advancing here would shift every later target.
        if choice.options.len() < 2 {
            return delegate(&mut self.inner);
        }
        // The bot still answers, because answering is what makes it compute and record the
        // position's features. Its choice is then discarded.
        let _ = delegate(&mut self.inner)?;

        let Some(wanted) = self.script.get(self.at).cloned() else {
            *self.broken.borrow_mut() = Some(format!(
                "the script ran out at decision {} of {}",
                self.at,
                self.script.len()
            ));
            return Err(IllegalChoice::DeciderFailed {
                player: choice.player.clone(),
                prompt: choice.prompt.clone(),
                reason: "replay script exhausted".to_owned(),
            });
        };
        self.at += 1;

        // By id, never by position: a position would silently select a different action if
        // anything about the offer had drifted, and the whole point of storing ids is that this
        // fails closed instead.
        let Some(index) = choice.options.iter().position(|option| option.id == wanted) else {
            *self.broken.borrow_mut() = Some(format!(
                "{wanted:?} was not offered at decision {}",
                self.at - 1
            ));
            return Err(IllegalChoice::DeciderFailed {
                player: choice.player.clone(),
                prompt: choice.prompt.clone(),
                reason: format!("recorded option {wanted:?} is not on offer"),
            });
        };
        self.forced.borrow_mut().push(index);
        Ok(choice.options[index].clone())
    }
}

impl Decider for Replaying {
    fn choose(&mut self, choice: &Choice) -> Result<ChoiceOption, IllegalChoice> {
        self.answer(choice, |inner| inner.choose(choice))
    }
    fn choose_seeing(
        &mut self,
        choice: &Choice,
        seen: &SeatObservation<'_>,
    ) -> Result<ChoiceOption, IllegalChoice> {
        self.answer(choice, |inner| inner.choose_seeing(choice, seen))
    }
}

struct Table<'a> {
    content: &'static ContentStore,
    factions: &'a [FactionId],
    pool: &'a Arc<ti4_sim::MapPool>,
    vocabulary: &'a ti4_policy::vocabulary::Vocabulary,
}

/// How the five opponents were sampled when a line was recorded.
///
/// The two corpora differ and neither records it. `build_positive_corpus` puts every seat at the
/// corpus temperature; `rescue_search` holds the opponents greedy and heats only the searching seat.
/// Replaying with the wrong convention faces different opponents, so the line does not exist and the
/// demonstration is silently lost.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Opponents {
    Greedy,
    SameTemperature,
}

/// Replay one stored trajectory and return its demonstrations.
fn demonstrate(
    table: &Table<'_>,
    // The **frozen** generating policy. Never the one being trained: see the module note.
    actor: &Rc<ti4_mlp::Actor>,
    trajectory: &Trajectory,
    opponents: Opponents,
) -> Result<Vec<Demo>, String> {
    type RecordLog = Rc<RefCell<Vec<ti4_mlp::bot::PpoRecord>>>;
    type RecordHandle = Rc<RefCell<Option<RecordLog>>>;
    let records: RecordHandle = Rc::new(RefCell::new(None));
    let forced = Rc::new(RefCell::new(Vec::new()));
    let broken = Rc::new(RefCell::new(None));
    let handle = Rc::clone(&records);
    let taken = Rc::clone(&forced);
    let fault = Rc::clone(&broken);
    let script = trajectory.decisions.clone();
    let want = trajectory.faction.clone();

    let played = ti4_training::rollout::audit_game_with_deciders(
        table.content,
        table.factions,
        DEFAULT,
        trajectory.seed,
        trajectory.rotation,
        ti4_training::rollout::Horizon {
            rounds: 1,
            steps: 200_000,
        },
        &ti4_training::rollout::OpeningMap::PythonPool {
            pool: Arc::clone(table.pool),
            tile_seed_offset: TILE_SEED_OFFSET,
        },
        |seated, baselines| {
            let mut deciders: BTreeMap<PlayerId, Box<dyn Decider>> = BTreeMap::new();
            for (index, (player, faction)) in seated.iter().enumerate() {
                let row = ti4_mlp::FactionRow::of(faction.as_str())
                    .map_err(|error| format!("{player}: {error}"))?;
                let baseline = baselines
                    .get(player)
                    .copied()
                    .ok_or_else(|| format!("{player} has no baseline"))?;
                // The generating temperature, for every seat, and the same stream offset. The
                // demonstration is a line played against five particular opponents; replaying at
                // any other setting faces different opponents and the recorded ids are not on
                // offer. Omitting this failed 59 of 60 replays.
                #[expect(
                    clippy::cast_precision_loss,
                    reason = "a temperature in thousandths, well within f64"
                )]
                let temperature = trajectory.temperature_milli as f64 / 1_000.0;
                let mine = faction.as_str() == want;
                let heated = mine || opponents == Opponents::SameTemperature;
                let stream = trajectory
                    .seed
                    .wrapping_mul(1_000_003)
                    .wrapping_add(u64::try_from(index).unwrap_or(0))
                    .wrapping_add(if heated {
                        trajectory.temperature_milli
                    } else {
                        0
                    });
                let bot =
                    ti4_mlp::bot::MlpBot::sharing(actor, table.vocabulary.clone(), row, stream)
                        .at_temperature(if heated { temperature } else { 0.001 })
                        .from_setup(baseline);
                if mine {
                    let bot = bot.recording_ppo(ti4_mlp::bundle::CriticMode::BatchMean);
                    *handle.borrow_mut() = Some(bot.ppo_records());
                    let (decider, _status) = bot.seat();
                    deciders.insert(
                        player.clone(),
                        Box::new(Replaying {
                            inner: decider,
                            script: script.clone(),
                            at: 0,
                            forced: Rc::clone(&taken),
                            broken: Rc::clone(&fault),
                        }),
                    );
                } else {
                    // The other five seats play their own policy on their own streams, which is
                    // what the demonstration was produced against.
                    let (decider, _status) = bot.seat();
                    deciders.insert(player.clone(), decider);
                }
            }
            Ok(deciders)
        },
    );

    if let Some(reason) = broken.borrow().clone() {
        return Err(format!(
            "{}/{} {}: {reason}",
            trajectory.seed, trajectory.rotation, trajectory.faction
        ));
    }
    played?;

    let records = records
        .borrow_mut()
        .take()
        .ok_or_else(|| format!("{} recorded nothing", trajectory.faction))?;
    let steps: Vec<ti4_mlp::ppo::Step> = records.borrow().iter().map(|r| r.step.clone()).collect();
    let forced = forced.borrow();
    if steps.len() != forced.len() {
        // The recorder and the replay must see the same decisions in the same order, or a target
        // belongs to the wrong position. Both skip forced choices; this checks it rather than
        // trusting it.
        return Err(format!(
            "{}/{} {}: {} recorded steps against {} forced decisions",
            trajectory.seed,
            trajectory.rotation,
            trajectory.faction,
            steps.len(),
            forced.len()
        ));
    }
    // One over the decision count, so a trajectory counts once however long it is. Averaging over
    // decisions instead made Hacan carry 1.8x the gradient of L1Z1X per trajectory -- 79.5
    // decisions against 43.8, almost all of it free transactions -- while the trainer called itself
    // balanced across factions. The caller multiplies in the per-faction share.
    #[expect(
        clippy::cast_precision_loss,
        reason = "a trajectory is tens of decisions"
    )]
    let per_decision = 1.0 / steps.len().max(1) as f64;
    Ok(steps
        .into_iter()
        .zip(forced.iter())
        .map(|(step, chosen)| Demo {
            row: step.row,
            head: step.head,
            options: step.options,
            chosen: *chosen,
            weight: per_decision,
        })
        .collect())
}

/// Records a seat's decisions without changing them, so waste can be measured beside clearance.
struct Watching {
    inner: Box<dyn Decider>,
    log: Rc<RefCell<Vec<ti4_mlp::positive_corpus::Note>>>,
}

impl Watching {
    fn record(&self, choice: &Choice, chosen: &ChoiceOption) {
        if choice.options.len() < 2 {
            return;
        }
        let head = ti4_mlp::capture_head(ti4_policy::learned::decision_head(choice));
        self.log.borrow_mut().push(ti4_mlp::positive_corpus::Note {
            head: head.to_owned(),
            chosen: chosen.id.clone(),
            declined: chosen.is_decline(),
        });
    }
}

impl Decider for Watching {
    fn choose(&mut self, choice: &Choice) -> Result<ChoiceOption, IllegalChoice> {
        let chosen = self.inner.choose(choice)?;
        self.record(choice, &chosen);
        Ok(chosen)
    }
    fn choose_seeing(
        &mut self,
        choice: &Choice,
        seen: &SeatObservation<'_>,
    ) -> Result<ChoiceOption, IllegalChoice> {
        let chosen = self.inner.choose_seeing(choice, seen)?;
        self.record(choice, &chosen);
        Ok(chosen)
    }
}

/// Greedy clearance and wasted-activation incidence on the validation pool.
///
/// Both, because the target is both: a policy is only wanted if it clears **and** wastes nothing,
/// and selecting on clearance alone would happily hand back one that pays for it in wasted turns.
fn measure(
    table: &Table<'_>,
    actor: &ti4_mlp::Actor,
    seeds: u64,
    seed_base: u64,
) -> Result<(f64, f64), String> {
    let jobs: Vec<(u64, usize)> = (seed_base..seed_base + seeds)
        .flat_map(|seed| (0..FACTIONS.len()).map(move |rotation| (seed, rotation)))
        .collect();
    let workers = rayon::current_num_threads().max(1);
    let per_worker = jobs.len().div_ceil(workers).max(1);
    let harvest: Vec<Result<(usize, usize, usize), String>> = jobs
        .chunks(per_worker)
        .map(|chunk| (actor.inference_copy(), chunk.to_vec()))
        .collect::<Vec<_>>()
        .into_par_iter()
        .map(|(local, chunk)| {
            let local = Rc::new(local);
            let (mut seats, mut cleared, mut wasteful) = (0usize, 0usize, 0usize);
            for (seed, rotation) in chunk {
                let mut logs: BTreeMap<PlayerId, Rc<RefCell<Vec<ti4_mlp::positive_corpus::Note>>>> =
                    BTreeMap::new();
                let (_e, _s, _a, openings, _f) = ti4_training::rollout::audit_game_with_deciders(
                    table.content,
                    table.factions,
                    DEFAULT,
                    seed,
                    rotation,
                    ti4_training::rollout::Horizon {
                        rounds: 1,
                        steps: 200_000,
                    },
                    &ti4_training::rollout::OpeningMap::PythonPool {
                        pool: Arc::clone(table.pool),
                        tile_seed_offset: TILE_SEED_OFFSET,
                    },
                    |seated, baselines| {
                        let mut deciders: BTreeMap<PlayerId, Box<dyn Decider>> = BTreeMap::new();
                        for (index, (player, faction)) in seated.iter().enumerate() {
                            let row = ti4_mlp::FactionRow::of(faction.as_str())
                                .map_err(|error| format!("{player}: {error}"))?;
                            let baseline = baselines
                                .get(player)
                                .copied()
                                .ok_or_else(|| format!("{player} has no baseline"))?;
                            let stream = seed
                                .wrapping_mul(1_000_003)
                                .wrapping_add(u64::try_from(index).unwrap_or(0));
                            let (decider, _status) = ti4_mlp::bot::MlpBot::sharing(
                                &local,
                                table.vocabulary.clone(),
                                row,
                                stream,
                            )
                            .at_temperature(0.001)
                            .from_setup(baseline)
                            .seat();
                            let log = Rc::new(RefCell::new(Vec::new()));
                            logs.insert(player.clone(), Rc::clone(&log));
                            deciders.insert(
                                player.clone(),
                                Box::new(Watching {
                                    inner: decider,
                                    log,
                                }),
                            );
                        }
                        Ok(deciders)
                    },
                )?;
                for (player, opening) in &openings {
                    seats += 1;
                    cleared += usize::from(opening.cleared());
                    if let Some(notes) = logs.get(player)
                        && ti4_mlp::positive_corpus::wasted_activations(&notes.borrow()) > 0
                    {
                        wasteful += 1;
                    }
                }
            }
            Ok((seats, cleared, wasteful))
        })
        .collect();
    let (mut seats, mut cleared, mut wasteful) = (0usize, 0usize, 0usize);
    for chunk in harvest {
        let (n, c, w) = chunk?;
        seats += n;
        cleared += c;
        wasteful += w;
    }
    if seats == 0 {
        return Err("no seat-games measured".to_owned());
    }
    #[expect(clippy::cast_precision_loss, reason = "counts are small")]
    Ok((
        cleared as f64 / seats as f64 * 100.0,
        wasteful as f64 / seats as f64 * 100.0,
    ))
}

#[expect(clippy::too_many_lines, reason = "one training loop")]
fn main() {
    let bundle_path = argument("--bundle").unwrap_or_else(|| refuse("--bundle is required"));
    let corpus_dir = argument("--corpus").unwrap_or_else(|| "out/corpus/positive".to_owned());
    // The rescued corpus is the only data from positions the policy actually loses. The ordinary
    // corpus is the stability distribution; this is the new information.
    let rescued_dir = argument("--rescued");
    // Share of each epoch drawn from the rescued corpus. Separate from the weighting, because how
    // much rescued data to *see* and how much to *weight* it are different questions.
    let rescued_share: f64 = number("--rescued-share", 0.5);
    let epochs: usize = number("--epochs", 20);
    let per_epoch: usize = number("--per-epoch", 1_200);
    let batch: usize = number("--batch", 60);
    let learning_rate: f64 = number("--learning-rate", 1e-5);
    let eval_seeds: u64 = number("--eval-seeds", 200);
    let out = argument("--out").unwrap_or_else(|| "out/checkpoints/cloned".to_owned());

    ti4_tensor::configure_deterministic(20_260_826)
        .unwrap_or_else(|error| refuse(&format!("configuring the backend: {error}")));
    let content = ContentStore::embedded();

    let loaded = ti4_mlp::bundle::read(std::path::Path::new(&bundle_path))
        .unwrap_or_else(|error| refuse(&format!("reading {bundle_path}: {error}")));
    let vocabulary = loaded.vocabulary;
    let mut actor = loaded.actor;
    // Replay must use the policy the corpus was generated by, or the recorded lines do not exist.
    // Training may start from a *different* policy -- typically a better one produced by an earlier
    // round of this same loop. Without separating them, every round would have to restart from the
    // original champion and discard its own gains.
    let frozen = match argument("--replay-bundle") {
        Some(path) => {
            ti4_mlp::bundle::read(std::path::Path::new(&path))
                .unwrap_or_else(|error| refuse(&format!("reading {path}: {error}")))
                .actor
        }
        None => actor.inference_copy(),
    };
    let slots_text = std::fs::read_to_string(std::path::Path::new(&bundle_path).join("slots.json"))
        .unwrap_or_else(|error| refuse(&format!("reading slots.json: {error}")));
    let git_commit = std::env::var("GIT_COMMIT")
        .unwrap_or_else(|_| refuse("GIT_COMMIT is required so checkpoints can be traced"));

    let train_pool = Arc::new(
        ti4_sim::MapPool::from_reader(std::io::Cursor::new(
            ti4_sim::artifacts::read_and_verify_pool_role(
                std::path::Path::new("out/pools/full_np8_12_train.json"),
                &[ti4_sim::artifacts::ArtifactRole::Train],
            )
            .unwrap_or_else(|error| refuse(&format!("train pool: {error}"))),
        ))
        .unwrap_or_else(|error| refuse(&format!("parsing the train pool: {error}"))),
    );
    let holdout_pool = Arc::new(
        ti4_sim::MapPool::from_reader(std::io::Cursor::new(
            ti4_sim::artifacts::read_and_verify_pool_role(
                std::path::Path::new("out/pools/full_np8_12_holdout.json"),
                &[ti4_sim::artifacts::ArtifactRole::Validation],
            )
            .unwrap_or_else(|error| refuse(&format!("holdout pool: {error}"))),
        ))
        .unwrap_or_else(|error| refuse(&format!("parsing the holdout pool: {error}"))),
    );
    let factions: Vec<FactionId> = FACTIONS.iter().map(|name| FactionId::new(*name)).collect();

    // ---- load the corpus ---------------------------------------------------------------------
    let load = |directory: &str| -> BTreeMap<String, Vec<Trajectory>> {
        let mut out: BTreeMap<String, Vec<Trajectory>> = BTreeMap::new();
        for faction in FACTIONS {
            let path = std::path::Path::new(directory).join(format!("{faction}.corpus"));
            let Ok(text) = std::fs::read_to_string(&path) else {
                continue;
            };
            let parsed = read_all(&text)
                .unwrap_or_else(|error| refuse(&format!("parsing {}: {error}", path.display())));
            for (name, rows) in parsed {
                out.entry(name).or_default().extend(rows);
            }
        }
        out
    };
    let ordinary = load(&corpus_dir);
    let rescued = rescued_dir.as_ref().map(|d| load(d)).unwrap_or_default();
    let ordinary_total: usize = ordinary.values().map(Vec::len).sum();
    let rescued_total: usize = rescued.values().map(Vec::len).sum();
    if ordinary_total == 0 {
        refuse("the ordinary corpus is empty");
    }
    let share = if rescued_total == 0 {
        0.0
    } else {
        rescued_share
    };

    println!("corpus training from {bundle_path}");
    println!("  ordinary   {corpus_dir}, {ordinary_total} trajectories");
    if let Some(directory) = &rescued_dir {
        println!(
            "  rescued    {directory}, {rescued_total} trajectories, {:.0}% of each epoch",
            share * 100.0
        );
    }
    println!("  per epoch  {per_epoch}, balanced across factions and sources");
    println!("  step       {learning_rate}");
    if argument("--replay-bundle").is_some() {
        println!(
            "  replay     {} (the corpus generator)",
            argument("--replay-bundle").unwrap_or_default()
        );
    }
    println!();

    let holdout_table = Table {
        content,
        factions: &factions,
        pool: &holdout_pool,
        vocabulary: &vocabulary,
    };
    // The waste ceiling a checkpoint must respect to be selected at all. Clearance alone would
    // happily pick a policy that pays for it in wasted turns.
    let waste_ceiling: f64 = number("--waste-ceiling", 100.0);
    let (baseline, baseline_waste) = measure(&holdout_table, &actor, eval_seeds, 900_000_000)
        .unwrap_or_else(|error| refuse(&error));
    println!(
        "  baseline   {baseline:.2}% greedy, {baseline_waste:.2}% of seats wasteful (ceiling {waste_ceiling}%)"
    );
    println!();

    let settings = ti4_mlp::ppo::Settings {
        learning_rate,
        ..ti4_mlp::ppo::Settings::default()
    };
    let mut optimizer =
        ti4_mlp::ppo::Adam::new(&mut actor, ti4_mlp::bundle::CriticMode::BatchMean, settings)
            .unwrap_or_else(|error| refuse(&format!("optimizer: {error}")));

    let mut best = baseline;
    let mut best_epoch = 0usize;
    let per_faction = per_epoch / FACTIONS.len();

    for epoch in 1..=epochs {
        let started = std::time::Instant::now();
        // Balanced draw. A raw pool would train twice as hard on Sol and L1Z1X purely because more
        // of their trajectories survived the filter.
        let mut drawn: Vec<(Trajectory, Opponents)> = Vec::new();
        #[expect(
            clippy::cast_possible_truncation,
            clippy::cast_sign_loss,
            reason = "a share of a per-epoch count"
        )]
        let rescued_each = (per_faction as f64 * share) as usize;
        let ordinary_each = per_faction.saturating_sub(rescued_each);
        let take = |rows: &Vec<Trajectory>,
                    want: usize,
                    convention: Opponents,
                    out: &mut Vec<(Trajectory, Opponents)>| {
            if rows.is_empty() || want == 0 {
                return;
            }
            // A stride rather than a prefix, so an epoch sees the whole seed range, and an offset
            // that moves with the epoch so successive epochs see different lines.
            let stride = (rows.len() / want).max(1);
            let offset = epoch.wrapping_mul(7919) % rows.len();
            for index in 0..want.min(rows.len()) {
                out.push((
                    rows[(offset + index * stride) % rows.len()].clone(),
                    convention,
                ));
            }
        };
        for faction in FACTIONS {
            if let Some(rows) = ordinary.get(faction) {
                take(rows, ordinary_each, Opponents::SameTemperature, &mut drawn);
            }
            if let Some(rows) = rescued.get(faction) {
                take(rows, rescued_each, Opponents::Greedy, &mut drawn);
            }
        }

        let mut seen = 0usize;
        let mut loss_sum = 0.0f64;
        let mut steps = 0usize;
        let mut failed = 0usize;

        for chunk in drawn.chunks(batch) {
            let workers = rayon::current_num_threads().max(1);
            let per_worker = chunk.len().div_ceil(workers).max(1);
            let harvest: Vec<(Vec<Demo>, usize)> = chunk
                .chunks(per_worker)
                .map(|piece| (frozen.inference_copy(), piece.to_vec()))
                .collect::<Vec<_>>()
                .into_par_iter()
                .map(|(local, piece)| {
                    let local = Rc::new(local);
                    let table = Table {
                        content,
                        factions: &factions,
                        pool: &train_pool,
                        vocabulary: &vocabulary,
                    };
                    let mut demos = Vec::new();
                    let mut bad = 0usize;
                    for (trajectory, convention) in piece {
                        match demonstrate(&table, &local, &trajectory, convention) {
                            Ok(mut rows) => demos.append(&mut rows),
                            Err(_) => bad += 1,
                        }
                    }
                    (demos, bad)
                })
                .collect();

            let mut demos: Vec<Demo> = Vec::new();
            for (mut rows, bad) in harvest {
                demos.append(&mut rows);
                failed += bad;
            }
            // The per-faction share. Every trajectory already carries `1 / its decisions`, so a
            // faction's mass in this batch is exactly the number of its trajectories; dividing by
            // that makes each faction contribute equally however many of its trajectories landed
            // here and however long they ran.
            let mut mass: BTreeMap<usize, f64> = BTreeMap::new();
            for demo in &demos {
                *mass.entry(demo.row.index()).or_default() += demo.weight;
            }
            for demo in &mut demos {
                if let Some(total) = mass.get(&demo.row.index())
                    && *total > 0.0
                {
                    demo.weight /= *total;
                }
            }
            if demos.is_empty() {
                continue;
            }
            seen += demos.len();

            optimizer
                .zero_grad(&actor)
                .unwrap_or_else(|error| refuse(&format!("clearing gradients: {error}")));
            let loss = ti4_mlp::positive_corpus::clone_loss(&actor, &demos)
                .unwrap_or_else(|error| refuse(&format!("clone loss: {error}")))
                .unwrap_or_else(|| refuse("the demonstration batch was empty"));
            loss_sum += f64::try_from(&loss).unwrap_or(f64::NAN);
            steps += 1;
            loss.backward();
            optimizer
                .step(&actor)
                .unwrap_or_else(|error| refuse(&format!("optimizer step: {error}")));
        }

        #[expect(clippy::cast_precision_loss, reason = "counts are small")]
        let mean_loss = loss_sum / steps.max(1) as f64;
        let (held, waste) = measure(&holdout_table, &actor, eval_seeds, 900_000_000)
            .unwrap_or_else(|error| refuse(&error));
        // Only a checkpoint under the ceiling can be the best. A run that clears more by wasting
        // more has not met the requirement, and calling it best would hide that.
        let admissible = waste <= waste_ceiling;
        let mark = if admissible && held > best {
            "  <-- best"
        } else if !admissible {
            "  (over the waste ceiling)"
        } else {
            ""
        };
        println!(
            "  epoch {epoch:>3}: {seen} demos, loss {mean_loss:.4}, held out {held:.2}%, waste {waste:.2}%{mark}  ({:.0?})",
            started.elapsed()
        );
        if failed > 0 {
            println!("             {failed} trajectories failed to replay");
        }

        let path = std::path::Path::new(&out).join(format!("epoch-{epoch}"));
        ti4_mlp::bundle::write(
            &path,
            &actor,
            &slots_text,
            ti4_mlp::bundle::CriticMode::BatchMean,
            &ti4_mlp::bundle::Provenance {
                source: "corpus_train".to_owned(),
                git_commit: git_commit.clone(),
                update: u64::try_from(epoch).unwrap_or(0),
            },
        )
        .unwrap_or_else(|error| refuse(&format!("writing {}: {error}", path.display())));

        if admissible && held > best {
            best = held;
            best_epoch = epoch;
        }
    }

    println!();
    println!("  baseline {baseline:.2}%  ->  best {best:.2}% (epoch {best_epoch})");
    if best <= baseline {
        println!("  NO IMPROVEMENT. Recorded as the result.");
    }
}
