//! Strategy-card draft choices.

use ti4_content::ContentStore;
use ti4_model::content_types::ContentType;
use ti4_model::id::PlayerId;
use ti4_model::state::GameState;

use crate::choice::{Choice, ChoiceOption, IllegalChoice, validate};
use crate::decision_context::{DecisionContext, DecisionSource};
use crate::phase::next_strategy_picker;

/// The stable option kind for a strategy-card selection.
pub const STRATEGY_CARD_KIND: &str = "strategy_card";

/// The draft cannot be applied to an inconsistent state or an option that was not offered.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DraftError {
    #[error("the strategy draft is complete")]
    Complete,
    #[error("the current strategy picker {0} is not a player")]
    MissingPicker(PlayerId),
    #[error("chosen strategy card {0:?} is no longer unclaimed")]
    CardNoLongerAvailable(String),
    #[error(transparent)]
    IllegalChoice(#[from] IllegalChoice),
}

/// The one legal choice at the current point in the strategy-card draft.
///
/// The returned ids are corpus strategy-card ids and are therefore stable decision-log
/// values.  Labels are deliberately human-readable (`"3. Politics"`), while an unknown
/// corpus id remains visible rather than vanishing from a legal choice.
#[must_use]
pub fn strategy_options(state: &GameState, content: &ContentStore) -> Option<Choice> {
    let picker = next_strategy_picker(state)?;
    let options = state
        .unclaimed_strategy_cards
        .iter()
        .map(|card| {
            ChoiceOption::labelled(
                card.as_str(),
                STRATEGY_CARD_KIND,
                strategy_card_label(content, card.as_str()),
            )
        })
        .collect();
    Some(
        Choice::new(picker.clone(), "choose a strategy card", options).contextualized(
            DecisionContext::new(
                picker,
                DecisionSource::Rule("26".to_owned()),
                "draft_strategy_card",
                state.phase,
                state.round,
            ),
        ),
    )
}

/// Validate and apply one generated strategy-card choice.
///
/// Every fallible condition is checked before state changes, so an invented card or a
/// malformed state cannot leave a card removed from the mat without being dealt.
///
/// # Errors
/// [`DraftError::Complete`] if no selection remains, or [`DraftError::IllegalChoice`] when
/// `answer` was not generated by the current choice.
pub fn take_strategy_card(
    state: &mut GameState,
    content: &ContentStore,
    answer: ChoiceOption,
) -> Result<PlayerId, DraftError> {
    let choice = strategy_options(state, content).ok_or(DraftError::Complete)?;
    let answer = validate(&choice, answer)?;
    let player = choice.player;
    if state.player(&player).is_none() {
        return Err(DraftError::MissingPicker(player));
    }
    let card_index = state
        .unclaimed_strategy_cards
        .iter()
        .position(|card| card.as_str() == answer.id)
        .ok_or_else(|| DraftError::CardNoLongerAvailable(answer.id.clone()))?;
    let card = state.unclaimed_strategy_cards[card_index].clone();

    // 91.1a: "If there are one or more trade good tokens on a strategy card when a player chooses
    // it, that player gains those trade goods." `stock_unclaimed_cards` has been putting a good on
    // every unchosen card at the end of every strategy phase, and Manipulate Investments puts five
    // more -- and nothing has ever collected them. The pile grew for the whole game and the
    // compensation for taking a low-initiative card was never paid.
    let goods = state.strategy_card_goods.remove(&card).unwrap_or(0);
    if goods > 0
        && let Some(seat) = state.player_mut(&player)
    {
        seat.trade_goods += goods;
        crate::supply::note_trade_goods_gained(state, &player, goods, "strategy_card");
    }

    // `player` was checked above, so the only mutation APIs used here cannot fail.
    let dealt = state.deal_strategy_card(&player, card);
    debug_assert!(dealt, "the checked strategy picker must be dealable");
    state.unclaimed_strategy_cards.remove(card_index);
    Ok(player)
}

pub(crate) fn strategy_card_label(content: &ContentStore, card_id: &str) -> String {
    let Some(card) = content.get(ContentType::StrategyCards, card_id) else {
        return card_id.to_owned();
    };
    let initiative = card
        .int("initiative")
        .map_or_else(|| "?".to_owned(), |number| number.to_string());
    let name = card.text("name").unwrap_or(card_id);
    format!("{initiative}. {name}")
}

#[cfg(test)]
mod tests {

    /// 91.1a: the trade goods sitting on a strategy card go to whoever takes it.
    ///
    /// `stock_unclaimed_cards` has put a good on every unchosen card at the end of every strategy
    /// phase, and Manipulate Investments puts five more. Nothing collected them: the pile grew for
    /// the whole game, `strategy_card_goods` was read into an event payload and an observation and
    /// never into anybody's trade goods, so the compensation for taking a late card was never paid.
    #[test]
    fn taking_a_card_collects_the_trade_goods_on_it() {
        let content = ContentStore::embedded();
        let mut state = crate::fixtures::game(&["a", "b"]);
        let player = state.speaker.clone();
        let choice = strategy_options(&state, content).expect("a draft is open");
        let card = ti4_model::id::StrategyCardId::new(choice.options[0].id.clone());
        state.strategy_card_goods.insert(card.clone(), 3);
        let before = state.player(&player).map_or(0, |seat| seat.trade_goods);

        let took = take_strategy_card(&mut state, content, choice.options[0].clone())
            .expect("the speaker takes a card");
        assert_eq!(took, player);

        assert_eq!(
            state.player(&player).map_or(0, |seat| seat.trade_goods),
            before + 3,
            "the three goods on the card were collected"
        );
        assert!(
            !state.strategy_card_goods.contains_key(&card),
            "and the card is empty afterwards, so they cannot be collected twice"
        );
    }

    /// OBS-003e: the strategy-card draft names its rule and a stable subtype.
    #[test]
    fn obs003e_strategy_draft_carries_its_typed_context() {
        let content = ContentStore::embedded();
        let state = crate::fixtures::game(&["a", "b"]);
        let choice = strategy_options(&state, content).expect("a draft is open");
        let context = choice.context.as_ref().expect("typed context");
        assert_eq!(context.source, DecisionSource::Rule("26".to_owned()));
        assert_eq!(context.subtype, "draft_strategy_card");
    }
    use ti4_content::ContentStore;
    use ti4_model::content_types::POK;
    use ti4_model::id::PlayerId;

    use super::*;
    use crate::choice::{Decider, FirstOption};
    use crate::setup::start_game;

    #[test]
    fn the_speaker_is_offered_every_unclaimed_strategy_card() {
        let players = [PlayerId::new("a"), PlayerId::new("b"), PlayerId::new("c")];
        let state = start_game(ContentStore::embedded(), &players, POK, None).unwrap();

        let choice = strategy_options(&state, ContentStore::embedded()).unwrap();

        assert_eq!(choice.player, PlayerId::new("a"));
        assert_eq!(choice.prompt, "choose a strategy card");
        assert_eq!(choice.options.len(), 8);
        assert!(
            choice
                .options
                .iter()
                .all(|option| option.kind == "strategy_card")
        );
        assert!(
            choice
                .options
                .iter()
                .all(|option| option.label.contains(". "))
        );
    }

    #[test]
    fn a_generated_choice_moves_exactly_one_card_to_its_picker() {
        let players = [PlayerId::new("a"), PlayerId::new("b"), PlayerId::new("c")];
        let mut state = start_game(ContentStore::embedded(), &players, POK, None).unwrap();
        let choice = strategy_options(&state, ContentStore::embedded()).unwrap();
        let answer = choice.options[3].clone();

        assert_eq!(
            take_strategy_card(&mut state, ContentStore::embedded(), answer.clone()).unwrap(),
            PlayerId::new("a")
        );
        assert_eq!(
            state
                .player(&PlayerId::new("a"))
                .unwrap()
                .strategy_cards
                .len(),
            1
        );
        assert!(
            !state
                .unclaimed_strategy_cards
                .iter()
                .any(|card| card.as_str() == answer.id)
        );
        assert_eq!(
            strategy_options(&state, ContentStore::embedded())
                .unwrap()
                .player,
            PlayerId::new("b")
        );
    }

    #[test]
    fn an_invented_strategy_card_leaves_the_draft_unchanged() {
        let players = [PlayerId::new("a"), PlayerId::new("b"), PlayerId::new("c")];
        let mut state = start_game(ContentStore::embedded(), &players, POK, None).unwrap();
        let before = state.clone();

        let error = take_strategy_card(
            &mut state,
            ContentStore::embedded(),
            ChoiceOption::new("invented", STRATEGY_CARD_KIND),
        )
        .unwrap_err();

        assert!(matches!(error, DraftError::IllegalChoice(_)));
        assert!(state.identical(&before));
    }

    #[test]
    fn first_option_can_complete_a_three_player_snake_draft() {
        let players = [PlayerId::new("a"), PlayerId::new("b"), PlayerId::new("c")];
        let mut state = start_game(ContentStore::embedded(), &players, POK, None).unwrap();
        let mut decider = FirstOption;
        let mut asked = Vec::new();

        while let Some(choice) = strategy_options(&state, ContentStore::embedded()) {
            asked.push(choice.player.clone());
            let answer = decider.choose(&choice).unwrap();
            take_strategy_card(&mut state, ContentStore::embedded(), answer).unwrap();
        }

        assert_eq!(
            asked,
            vec!["a", "b", "c", "c", "b", "a"]
                .into_iter()
                .map(PlayerId::new)
                .collect::<Vec<_>>()
        );
        assert!(
            state
                .players
                .iter()
                .all(|player| player.strategy_cards.len() == 2)
        );
        assert_eq!(state.unclaimed_strategy_cards.len(), 2);
    }
}
